# Site settings
title: "Project Timeline"
email: your-email@example.com
description: "A chronological journey through my projects and work"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.27.3
minimal_mistakes_skin: "default"

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Author
author:
  name: "Your Name"
  bio: "A timeline of projects and achievements."

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
