# Site settings
title: "Brad Dougherty's Projects"
email: your-email@example.com
description: "A chronological timeline of my projects and work over the years"
baseurl: ""
url: "https://projects.brad-dougherty.com"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.27.3
minimal_mistakes_skin: "default"

# Outputting
permalink: /:categories/:title/
paginate: 10
paginate_path: /page:num/

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Author
author:
  name: "Brad Dougherty"
  bio: "Building things over the years. This is a timeline of my projects and technical journey."
  location: "United States"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/potable-anarchy"

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
      show_date: true
EOF </dev/null
